---
title: "c2d4u Update: 230 New and Updated Pacakges"
date: 2018-05-27T19:01:26-04:00
draft: false
tags: [R, c2d4u, Ubuntu]
topics: [R, c2d4u, Ubuntu]
description: ""
---

On the c2d4u PPAs, my goal is to update and add new packages (from CRAN Task Views) on a weekly basis, usually on the weekend.  While I was building c2d4u3.5, I put this on hold, as I didn't want to build new (to the PPA) packages at the same time as checking old ones.

For this update, 230 R packages were either updated or added as new.  At this time, I don't provide information that distinguishes between updated or new, but that feature may be added in the future.  The list of all packages is given in the table below.

Of all the packages updated today, only one failed to build a source package without intervention: [m2r](https://cran.r-project.org/web/packages/m2r/index.html).  This package is an interface to [Macaulay2](http://www.math.uiuc.edu/Macaulay2/), a software system supporting research in algebraic geometry and commutative algebra.  This type of interface package is fairly common, and the reason it fails to build a source package is that Macaulay2 is a system requirement (according to CRAN).  While packages are available on the website and they have [repository](https://faculty.math.illinois.edu/Macaulay2/Repositories/Ubuntu/dists/) (similar the the CRAN Ubuntu repository), it is not a PPA and therefore not available in Launchpad.

In these types of cases, where a package is just an interface to a non-R package that is assumed to be on the system, I ignore that system requirement.  The downside is that a user can install r-cran-m2r and it will not work, because they still need to install Macaulay2.  There really is now way around this limitation (unless the Macaulay2 maintainers start a PPA), but in most cases the users of these specialized packages already have the needed software on their system.  I am just providing an easy install/update path.

```{r echo=FALSE}
library(XML)
library(knitr)
url <- "http://192.168.1.129/cran2deb/todays_packages.html"
new.pkgs <- readHTMLTable(url)[[2]]
kable(new.pkgs[,4:5])
```




