---
title: "Update on the Move to R 3.5.0"
date: 2018-05-20T12:50:00-05:00
draft: false
tags: [R,Ubuntu,c2d4u]
categories: [R,Ubuntu,c2d4u]
description: ""
---

I am slowly rebuilding the set of packages in [c2d4u](https://launchpad.net/~marutter/+archive/ubuntu/c2d4u/+packages) for use with R 3.5.0.  Since packages built under version 3.4.* are not compatible with 3.5.0, they all need to be rebuilt.  This includes the packages that came with the new Ubuntu Bionic (18.04) release.  It is taking some time.

One of the challenges with using Launchpad is that once a package is built, it needs to be published.  This takes some time (around 20 minutes).  Therefore, you can't just push a series of packages to Launchpad and walk away.  In order to ensure the dependencies are built, you need to wait until they have been published in the PPA.  This is on top of determining the build order based on dependencies.

So part of the process has been writing an R script that takes a set of packages from a Task View, creates the dependency tree, and then determines which of the packages (could be 300+ with dependencies) are already available on the PPA.  I also check to see if the most recent version is on the PPA.  Then from the packages that need to be built, I determine which need to be built first, second, etc.  Each set is sent to Launchpad, then I watch to see when the last package is published using the Launchpad API.  I wait another four minutes (the API is a little premature), then send the next batch.

Now that the bugs have been worked out, things are running smoothly.  As I post this, the new repository has 1583 packages published for Xenial.  In the current c2d4u PPA, there are 3783 packages for Xenial.

As all the packages are not built yet, updating to R 3.5.0 via my PPAs will still break your system, which is why I have not officially announced the new PPA yet.  As soon as the project is completed, I will let you know.

