---
title: "June 11th, 2018 R 3.5.0 on Debian and Ubuntu: An Update"
date: 2018-06-10T11:20:33-05:00
draft: false
tags: [R,3.5,Ubuntu,Debian]
categories: [R,3.5,Ubuntu,Debian]
description: ""
---

# Overview

R 3.5.0 was [released](https://stat.ethz.ch/pipermail/r-announce/2018/000628.html) a few weeks ago. As it changes some (important) internals, packages installed with a previous version of R have to be rebuilt. This was known and expected, and we took several measured steps to get R binaries to everybody without breakage.

The question of *but how do I upgrade without breaking my system* was asked a few times, *e.g.*, on the [r-sig-debian list](https://stat.ethz.ch/mailman/listinfo/r-sig-debian) as well as in [this StackOverflow question](https://stackoverflow.com/a/50076739/143305). 


# Debian

**Core Distribution**
As usual, we packaged R 3.5.0 as soon as it was released -- but only for the `experimental` distribution, awaiting a green light from the release masters to start the transition.   A one-off repository `[drr35](https://github.com/eddelbuettel/drr35)` was created to provide R 3.5.0 binaries more immediately; this was used, *e.g.*, by the `r-base` [Rocker Project](https://www.rocker-project.org/) container / the [official R Docker container](https://hub.docker.com/_/r-base/) which we also update after each release.

The actual transition was started last Friday, June 1, and concluded this Friday, June 8.  Well over 600 packages have been rebuilt under R 3.5.0, and are now ready in the `unstable` distribution from which they should migrate to `testing` soon.  The `Rocker` container `r-base` was also updated.

So if you use Debian unstable or testing, these are ready now (or will be soon once migrated to `testing`).   This should include most `Rocker` containers built from Debian images.

**Contributed CRAN Binaries**
Johannes also provided backports with a -`cran35` suffix in his CRAN-mirrored Debian backport repositories, see the [README](https://cloud.r-project.org/bin/linux/debian/).


# Ubuntu

**Core (Upcoming) Distribution** 
Ubuntu, for the upcoming 18.10, has undertaken a similar transition. Few users access this release yet, so the next section may be more important.

**Contributed CRAN and PPA Binaries**
Two new Launchpad PPA repositories were created as well.  Given the rather large scope of thousands of packages, multiplied by several Ubuntu releases, this too took a moment but is now fully usable and should get mirrored to CRAN ‘soon’.  It covers the most recent and still supported LTS releases as well as the current release 18.04.

One PPA contains base R and the recommended packages, [RRutter3.5](https://launchpad.net/~marutter/+archive/ubuntu/rrutter3.5).  This is source of the packages that will soon be available on CRAN.  The second PPA ([c2d4u3.5](https://launchpad.net/~marutter/+archive/ubuntu/c2d4u3.5)) contains over 3,500 packages mainly derived from [CRAN Task Views](https://cran.r-project.org/web/views/).  Details on updates can be found at Michael’s [R Ubuntu Blog](http://rubuntu.netlify.com/).

This can used for, *e.g.*, Travis if you managed your own sources as Dirk’s `r-travis` does. We expect to use this relatively soon, possibly as an opt-in via a variable upon which `run.sh` selects the appropriate repository set. It will also be used for `Rocker` releases built based off Ubuntu.

In both cases, you may need to adjust the `sources` list for `apt` accordingly. 


# Others

There may also be ongoing efforts within Arch and other Debian-derived distributions, but we are not really aware of what is happening there.  If you use those, and coordination is needed, please feel free to reach out via the the [r-sig-debian list](https://stat.ethz.ch/mailman/listinfo/r-sig-debian). 


# Closing

In case of questions or concerns, please consider posting to the [r-sig-debian list](https://stat.ethz.ch/mailman/listinfo/r-sig-debian).

Dirk, Michael and Johannes,  June 2018

